name: Benchmark

on: [push]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang
      - name: Build
        run: make
      - name: Create 10MB random file
        run: dd if=/dev/urandom of=random.txt bs=1M count=10
      - name: Run benchmark
        run: /usr/bin/time -v ./build/arc --benchmark random.txt
